bexmlsrv: use a WebPyMimeRender instance for mimerender.
With the earlier implementation,

  from mimerender import mimerender

was raising:

  ImportError: cannot import name mimerender

Looking through the history of mimerender [1], I couldn't find a time
where the old BEXML approach would work.  The new way works with
mimerender's commit b2dc6900.

[1]: http://github.com/martinblech/mimerender